<?php

declare(strict_types=1);

namespace OWC\Zaaksysteem\Entities;

use DateTimeImmutable;

class Taak extends Entity
{
    protected array $casts = [
        'verloopdatum' => Casts\NullableDate::class,
        'vervaldatum' => Casts\NullableDate::class,
        'zaak' => Casts\Lazy\Zaak::class,
    ];

    public function title(): string
    {
        return $this->getValue('title', '');
    }

    public function identification(): string
    {
        return $this->getValue('identificatie', '');
    }

    public function clarification(): string
    {
        return $this->getValue('toelichting', '');
    }

    public function expirationDate(string $format = 'j F Y'): string
    {
        $expirationDate = $this->getValue('verloopdatum', null);

        if (! $expirationDate instanceof DateTimeImmutable) {
            return '';
        }

        return date_i18n($format, $expirationDate->getTimestamp());
    }

    public function dueDate(string $format = 'j F Y'): string
    {
        $dueDate = $this->getValue('vervaldatum', null);

        if (! $dueDate instanceof DateTimeImmutable) {
            return '';
        }

        return date_i18n($format, $dueDate->getTimestamp());
    }

    public function zaaktypeObjectURL(): string
    {
        $data = $this->getData();

        return $data['zaakTypeUrl'] ?? '';
    }

    public function informationObjectURL(): string
    {
        $data = $this->getData();

        return $data['documentTypeUrl'] ?? '';
    }

    protected function getData(): array
    {
        return $this->getValue('data', []);
    }

    public function supplier(): string
    {
        $data = $this->getExtraData();

        return $data['leverancier'] ?? '';
    }

    protected function getExtraData(): array
    {
        return $this->getValue('extraData', []);
    }

    /**
     * Is used in overview generated by owc/mijn-taken block.
     */
    public function permalink(): string
    {
        $supplier = $this->supplier();

        if (empty($supplier)) {
            return sprintf('%s/taak/%s', get_site_url(), $this->getValue('id', ''));
        }

        return sprintf('%s/taak/%s/%s', get_site_url(), $this->getValue('id', ''), strtolower($supplier));
    }
}
